version: "3.7"

services:
  backend:
    build: ./backend
    image: backend-img
    container_name: "eather-backend"
    restart: always
    ports:
      - 8000:8000
    networks:
      - eathernet

  redis:
    image: redis:latest
    container_name: "eather-redis"
    ports:
      - 6379:6379
    networks:
      - eathernet

  db:
    image: postgres:latest
    container_name: "eather-postgres"
    ports:
      - 5432:5432
    networks:
      - eathernet
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d/
      - ./pg-data:/var/lib/postgresql/data

networks:
  eathernet:
    external: true
