version: "3.7"

services:
  db:
    image: postgres:latest
    container_name: "eather-postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: "eather-redis"
    ports:
      - 6379:6379

  backend:
    build: ./backend
    image: backend-img
    container_name: "eather-backend"
    restart: always
    links:
      - db
      - redis
    ports:
     - 8000:8000
    environment:
      - REDIS_URL=redis://eather-redis

