version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  backend:
    build: ./backend
    image: backend-img
    restart: always
    depends_on:
      - db
      - redis
    ports:
     - 8000:8000

